server:
  port: 16378
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # ????????
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/eat_big_turntable?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



system:
  jwt:
    secretKey: "tony chopper"
wexi:  # 微信小程序配置
  appid: "wxfbf664952970b1bb"
  secret: "9a8381b008724997047978c6b8966bf3"
  grant_type: "authorization_code"
