server:
  port: 16378
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 德鲁伊数据库连接池
    username: root
    password: 123456 # Yanwenguang123_
#    url: jdbc:mysql://www.sunnygo.chat:3307/eat_big_turntable?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/eat_big_turntable?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 30MB
  # =========================邮件服务=======================
  mail:
    host: smtp.qq.com # qq的smtp邮件发送服务器地址
    username: 3267585160@qq.com
    password: sniodluqoqaidaej # 第三方密码服务授权码
    properties:  # 下面设置属性，开启ssl连接，因为服务器需要使用ssl进行连接
      mail:
        smtp:
          ssl:
            enable: true
    port: 465
    custom-to: 3267585160@qq.com # 自定义发送汇总信息给指定邮箱
  thymeleaf:
    cache: false # 开发环境关闭缓存 生产环境打开缓存
  security:
    oauth2:
      authorizationserver:
        client:

# ================= mybatis-plus服务=================
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # org.apache.ibatis.logging.nologging.NoLoggingImpl

minio:
  endpoint: http://118.195.164.246:9000 # 连接点地址
  accessKey: yan  # 账号
  secretKey: Yanwenguang123_  # 密码
  bucketName: planet

#=================自定义微信系统属性============
system:
  jwt:
    secretKey: "tony chopper"
wexi:  # 微信小程序配置
  appid: "wxfbf664952970b1bb"
  secret: "9a8381b008724997047978c6b8966bf3"
  grant_type: "authorization_code"
  mini_program_status: "developer"

#============================腾讯地图访问配置信息==============
tencent:
  secret-key: fi7lyF6Ng82zEEXZnhnIuDwpYEEFxTAE

#========================lombook日志配置=====================
logging:
  level:
    root: INFO              # 设置全局日志级别为 INFO，即默认输出 INFO、WARN、ERROR 级别的日志
    com.example: DEBUG      # 针对包 com.example 设置日志级别为 DEBUG，可输出 DEBUG 及以上级别日志
  file:
    name: /www/java_server/eat_bigger_turntable/console.log     # 指定日志输出文件路径，相对路径相对于项目根目录
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      # 定义日志文件的输出格式：
      # %d{...} → 日期时间
      # [%thread] → 当前线程名
      # %-5level → 日志级别，左对齐，占5个字符
      # %logger{36} → 输出类名，最多36个字符
      # %msg → 日志消息内容
    # %n → 换行符
# ================================第三方服务相关参数配置===================
thrids:
  badu:
    appid: "20251023002481706" # 百度翻译的appid
#    key: "vMgN2FcoeZxKSMBnaZz8" # 访问密钥
    apiKey: "Pbmz_d3vku6l0gkilp1858trg"   # 建议使用apikey来作为接口请求凭证
  cat:
    key: "live_3c2NvI7ceaFoCm9wfXEIuoPIEkiP2wjHODoN2bErSJQEGAHDQBajbTct3yKkJ8vH" # https://thecatapi.com/ 开发者密钥

# ================================用户相关配置===================

user:
  limitUpload: 1 # 用户账单上传图片附件限制数量

# ================================AI大模型相关配置==============
LLM:
  deepseek:
    api-key: sk-07de5615f2b04afaa9c2b3c1246c4757
    base-url: https://api.deepseek.com/
