server:
  port: 16378
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # ????????
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/eat_big_turntable?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

